Add No Props Destructure rule issue #143
rrd108/vue-mess-detector pull request #158
Opened 2024-08-19 21:02 UTC by sagi-daniel

### Summary
Létrehoztam egy új szabályt, amely a Vue komponensekben alkalmazott props destructuring gyakorlatát ellenőrzi. A szabály célja, hogy biztosítsa a kód olvashatóságát, karbantarthatóságát és működését, elkerülve a props változásának helytelen kezeléséből adódó problémákat.

A dokumentációt is elkészítettem, amely részletesen bemutatja a props destructuring problémáit és azok hatását a Vue komponensekre, a többi dokis mintájára hagyatkozva.

### Description
Alap Destructuring Ellenőrzés: Ellenőrzi, hogy a props destrukturálása nem történik-e meg a defineProps közvetlen használatával, ami reaktivitási problémákhoz vezethet. 

### Related Issues
Fixes #143 

### Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x ] Documentation update

2024-08-19 21:05 UTC, David-Pena commented
I think you have a a different linter setup? 🤔 @rrd108

2024-08-19 22:26 UTC, sagi-daniel commented
I have no idea, I'll check my vs code tomorrow.

On Mon, 19 Aug 2024 at 23:05, David Peña Avila ***@***.***>
wrote:

> I think you have a a different linter setup? 🤔 @rrd108
> <https://github.com/rrd108>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/rrd108/vue-mess-detector/pull/158#issuecomment-2297455591>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXSN2LHXWZZ6R3LHO5FLTVLZSJM3BAVCNFSM6AAAAABMYSQGFSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEOJXGQ2TKNJZGE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-08-19 22:31 UTC, David-Pena commented
No no I deleted my comment. It was my mistake 🫡

2024-08-20 07:15 UTC, rrd108 commented
@sagi-daniel I have a few requests and comments about the PR.

Are you ok with English or should I do it in Hungarian?

2024-08-20 08:43 UTC, sagi-daniel commented
> @sagi-daniel I have a few requests and comments about the PR.
> 
> Are you ok with English or should I do it in Hungarian?

Yes, totaly. We can speak in english. It s good opportunity improve my soft skills and hard skills at the same time.

2024-08-20 11:52 UTC, rrd108 commented
I didn't commented yet as was waiting for your answer.

The first thing:
When you open the project it supposed to ask you to install the recommended extensions. One of them is eslint.

It helps us to follow the same formatting.

Please install it. 

When you open any of the files you changed and do formatting it should remove the semicolumns.

Now it is harder to review the pr because I do not see what is code change at what is code change.

After you fixed it you should just commit the changes, it will update the pr and I will review that.

I am in a car this afternoon so I may need some time to check it.

And the most important part, thanks for the contribution!

2024-08-20 12:00 UTC, sagi-daniel commented
> I didn't commented yet as was waiting for your answer.
> 
> The first thing: When you open the project it supposed to ask you to install the recommended extensions. One of them is eslint.
> 
> It helps us to follow the same formatting.
> 
> Please install it.
> 
> When you open any of the files you changed and do formatting it should remove the semicolumns.
> 
> Now it is harder to review the pr because I do not see what is code change at what is code change.
> 
> After you fixed it you should just commit the changes, it will update the pr and I will review that.
> 
> I am in a car this afternoon so I may need some time to check it.
> 
> And the most important part, thanks for the contribution!

Thank you! I m going to install it, I thought npm install added all necessary depedency... maybe i didnt recognize some npm warning while the project initialization.

question: Do I have to make a new branch before the PR? or just push it to the main?

2024-08-20 12:22 UTC, rrd108 commented
It is not npm, they are vscode extensions.

You can create a new branch, but not necesarry as the PR will be merged in one step anyway.

2024-08-20 13:52 UTC, rrd108 requested changes

2024-08-20 13:52 UTC, rrd108 commented on docs/.vitepress/config.ts
> +    'A static code analysis tool for detecting code smells and best practice violations in **Vue** and **Nuxt** projects.',
There is still some formatting issue. In this file you have added one line but practically all lines marked as changed.

Can you take a look?

2024-08-20 13:52 UTC, rrd108 commented on docs/rules/rrd/no-props-destructure.md
> +Check if props are being destructured in a way that might affect readability, maintainability, or functionality.
Please mention the problem here. 

Destructing break reactivity

2024-08-20 13:52 UTC, rrd108 commented on docs/rules/rrd/no-props-destructure.md
> +While destructuring can simplify code in many cases, it can lead to issues with Vue's reactivity system. When props are destructured, Vue may not be able to track changes to the destructured properti
Not "may" happen. It will happens

2024-08-20 13:52 UTC, rrd108 commented on docs/rules/rrd/no-props-destructure.md
> +- Readability: Destructuring props can make the code cleaner and more readable by directly accessing individual properties. This can help in understanding the component’s requirements and logic more
Here you should state more clearly that destructing is not recommended at all.

2024-08-20 13:52 UTC, rrd108 commented on docs/rules/rrd/no-props-destructure.md
> +<script setup>
Nice and clear example but defineProps missing its parameters

2024-08-20 13:52 UTC, rrd108 commented on docs/rules/rrd/no-props-destructure.md
> +<script setup>
Please use the same example as in the other code above

2024-08-20 13:52 UTC, rrd108 commented on src/rules/rrd/noPropDestructure.ts
> +  const regex = /(?:const|let|var)\s*\{\s*([^\}]+)\s*\}\s*=\s*defineProps\s*\(\s*\)/g
You can remove var here. It will offend a new rule coming

2024-08-20 13:52 UTC, rrd108 commented on src/rules/rules.ts
> +    'noPropDestructure',
Keep the rules in alphabetic order

2024-08-20 13:52 UTC, rrd108 commented on src/rulesReport.ts
> +      if (health.some((h) => h.file === offense.file)) {
At `(h)` the bracets can be omitted. Also some formatting issue

2024-08-20 16:31 UTC, David-Pena commented
I think its important to add that is possible to destructure `props` but using `toRefs()`

Example
```
<script setup>
const props = defineProps<{ name: string }>()
const { name } = toRefs(props) // It will keep reactivity
</script>
```

What do you think? @rrd108 @sagi-daniel

2024-08-20 16:36 UTC, rrd108 commented
> I think its important to add that is possible to destructure `props` but using `toRefs()`
> 
> Example
> 
> ```
> <script setup>
> const props = defineProps<{ name: string }>()
> const { name } = toRefs(props) // It will keep reactivity
> </script>
> ```
> 
> What do you think? @rrd108 @sagi-daniel

`toRefs` approach is worth a dedicated rule. Keep this one here clear and simple.

2024-08-21 08:13 UTC, rrd108 approved these changes

2024-08-21 08:18 UTC, merged