added noVarDeclaration rule
rrd108/vue-mess-detector pull request #172
Opened 2024-08-21 23:38 UTC by sagi-daniel

### Summary
Add a new rule to disallow the use of var keyword for variable declarations

### Description
This change introduces a new rule in the codebase that enforces the use of const or let instead of the var keyword for variable declarations. The rule aims to modernize the code by avoiding the use of var, which has function scope and can lead to unexpected behavior due to its hoisting characteristics.

### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update

2024-08-22 03:47 UTC, David-Pena requested changes
Please check higlighted sections

2024-08-22 03:47 UTC, David-Pena commented on docs/rules/rrd/no-var-declaration.md
> +### Key Issues with var:
```suggestion
### Key Issues with `var`:
```

Add some backticks around var for consistency and to properly format it as code

2024-08-22 03:47 UTC, David-Pena commented on docs/rules/rrd/no-var-declaration.md
> +To ensure better scoping and avoid issues related to `var`, use `let` and `const` instead. Here’s how to replace `var` with let and const:
```suggestion
To ensure better scoping and avoid issues related to `var`, use `let` and `const` instead:
```

The last line was redundant

2024-08-22 03:47 UTC, David-Pena commented on docs/rules/rrd/no-var-declaration.md
> +- They help prevent bugs that arise from the quirks of var and improve overall code quality.
```suggestion
## ❓ Why it's good to follow this rule?

- **Predictable Behavior:** `let` and `const` provide block scope, which makes variable behavior more predictable and avoids issues related to variable hoisting and function scoping.
- **Improved Reactivity:** Using `let` and `const` helps maintain the integrity of Vue’s reactivity system by avoiding potential pitfalls associated with var.
- **Better Code Quality**: `let` and `const` promote clearer and more maintainable code and help prevent bugs that arise from the quirks of `var`.
```

I think we should stick to the layout in all markdown files. To enforce consistency across the codebase.

2024-08-22 03:47 UTC, David-Pena commented on docs/rules/rrd/no-var-declaration.md
> +Incorrect Usage:
```suggestion
## 😱 Examples of code for which this rule will throw a warning
```

2024-08-22 03:47 UTC, David-Pena commented on src/rules/rrd/noVarDeclaration.ts
> +        rule: `${TEXT_INFO}rrd ~ no Var Declaration${TEXT_RESET}`,
```suggestion
        rule: `${TEXT_INFO}rrd ~ No Var Declaration${TEXT_RESET}`,
```

This change is needed in the test file, it should be fixed there too

2024-08-22 03:47 UTC, David-Pena commented on src/rules/rules.ts
> +  'rrd': [
```suggestion
  rrd: [
```

2024-08-22 03:47 UTC, David-Pena commented on docs/rules/rrd/no-var-declaration.md
> +```
This example code should be from one of the test cases to enforce consistency 👀

2024-08-28 02:43 UTC, David-Pena commented
Hi @sagi-daniel let me know if you need any help 🫡

2024-08-28 07:00 UTC, sagi-daniel commented
> Hi @sagi-daniel let me know if you need any help 🫡

How can i refresh my fork? :S

2024-08-28 07:17 UTC, closed without merging

2024-08-28 07:20 UTC, David-Pena commented
> How can i refresh my fork? 😃 

You go to your repositories, find the fork. And there must be a button called "Sync" and it opens a mini popup with the option to "Update" your branch

2024-08-28 07:25 UTC, sagi-daniel commented
> > How can i refresh my fork? 😃
> 
> @sagi-daniel You go to your repositories, find the fork. And there must be a button called "Sync" and it opens a mini popup with the option to "Update" your branch
> 
> Are you going to open a new PR? We can reopen this one 👀

i cannot sync without discard :S, or maybe i was noob a little bit :P but now my fork is up to date, so i can reopen somehow?

2024-08-28 07:28 UTC, David-Pena commented
It doesn't let me reopen it, so check if you can do it:

If you can,
- checkout to this PR branch, and run git pull origin main
- Stage, commit and push your changes to the same branch 

If you can not, just open a new PR

2024-08-28 09:53 UTC, David-Pena commented
> opened in https://github.com/rrd108/vue-mess-detector/pull/192

Assign me as reviewer, I'll check it out in a moment